import { UTMTemplate } from "./types";

export const BUILT_IN_TEMPLATES: UTMTemplate[] = [
  {
    id: "ga4-standard",
    name: "Google Analytics 4 (Standard)",
    description: "Standard configuration for Google Search & general campaigns.",
    isBuiltIn: true,
    utmSource: "google",
    utmMedium: "organic",
    utmCampaign: "search_campaign",
  },
  {
    id: "google-ads-cpc",
    name: "Google Ads (Paid Search / CPC)",
    description: "Configured for Google Search Ads with dynamic match type placeholders.",
    isBuiltIn: true,
    utmSource: "google",
    utmMedium: "cpc",
    utmCampaign: "search_brand_ads",
    utmTerm: "{keyword}",
    customParams: [
      { key: "gclid", value: "{gclid}" },
      { key: "device", value: "{device}" },
    ],
  },
  {
    id: "facebook-ads",
    name: "Facebook Ads (Paid Social)",
    description: "Pre-populated with Facebook Ads dynamic markup variables for automated tracking.",
    isBuiltIn: true,
    utmSource: "facebook",
    utmMedium: "paid-social",
    utmCampaign: "{{campaign.name}}",
    utmContent: "{{adset.name}} - {{ad.name}}",
  },
  {
    id: "linkedin-sponsored",
    name: "LinkedIn Sponsored (Paid Social)",
    description: "Designed for LinkedIn sponsored posts and text campaigns.",
    isBuiltIn: true,
    utmSource: "linkedin",
    utmMedium: "paid-social",
    utmCampaign: "lead_generation_2026",
    utmContent: "image_ad_v1",
  },
  {
    id: "newsletter-blast",
    name: "Email Newsletter Blast",
    description: "Standard parameters for monthly newsletter email blasts.",
    isBuiltIn: true,
    utmSource: "newsletter",
    utmMedium: "email",
    utmCampaign: "newsletter_july_2026",
    utmContent: "header_cta",
  },
  {
    id: "twitter-organic",
    name: "Twitter / X (Organic Social)",
    description: "Shorthand parameters for general organic posts on Twitter/X.",
    isBuiltIn: true,
    utmSource: "x",
    utmMedium: "social-organic",
    utmCampaign: "summer_launch",
  },
  {
    id: "affiliate-marketing",
    name: "Affiliate Partner Link",
    description: "Configured for external affiliate partner tracking codes.",
    isBuiltIn: true,
    utmSource: "affiliate",
    utmMedium: "partner",
    utmCampaign: "affiliate_promo",
    utmId: "partner_id_100",
  },
];
